### ISSUE TITLE
Herons review

### ISSUE THREAD

**Issue by vzdrizhni** [vzdrizhni/private-events#1]
** To improve **
- Use more parameters

**Comment by rammazzoti2000** [comment]
# Changes Required :rage: 
- [ ] Get some rest :sleeping_bed: 
- [ ] Do not wake up until next week :timer_clock:

**Comment by vzdrizhni** [comment]
Спасибо за заботу, обязательно отдохну.

**Comment by rammazzoti2000** [comment]
Спасибо, позаботься о своей заднице

**Comment by vzdrizhni** [comment]
Îți mulțumesc că ai grijă atât de mult de fundul meu
