### ISSUE TITLE
Peer to Peer core review 

### ISSUE THREAD

**Issue by rammazzoti2000** [vzdrizhni/private-events#4]
Please leave your comments

**Comment by Kyle-Law** [comment]
Looks good to me 👍  Few findings here, correct me if I’m wrong:
- May write some data in seeds.rb so that user could test it with some initial data instead of re-creating them.
- In users, password_digest column is not needed, may remove it. 

That’s all from me. Great UI and RSpec testing 🥇

**Comment by patriciachrysy** [comment]
DOn't know about the rspec on rails yet but yours seem to be so detailed!! Great job on this project!

**Comment by nyatindopatrick** [comment]
Looks great! Good work.

**Comment by dili021** [comment]
@Kyle-Law password_digest is necessary when using has_secure_password, but since that is commented out, yes in this case it's not needed.
Great work Alex, you have entered the matrix! 01010111000010101
